name: diagrams.net site
permalink: /blog/:slug

url: ''
baseurl: '/'


collections:
  - faq

faq-categories: [Confluence Cloud, Confluence Server, Jira Cloud, Jira Server, Customisation, Shapes, Connectors, Plugins, Integrations, Export, Gliffy, Trust, Desktop, Import, Lucidchart, Features]
