name: diagrams.net site
permalink: /blog/:slug

url: ''
baseurl: '/'


collections:
  - faq

faq-categories: [Confluence Cloud, Confluence Server, Jira Cloud, Jira Server, Desktop, Trust, Features, Customisation, Shapes, Connectors, Plugins, Integrations, Export, Import, Troubleshooting, Gliffy, Lucidchart]
