name: Publish to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: fabacab/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_TOKEN }}
          post_build_commands: |
            mv assets/CNAME /CNAME
            mv assets/favicon.ico /favicon.ico
